### PR TITLE
Record tracks while playing

### PR DESCRIPTION
**Pull request by rupel190**
Heyo, this adds a recording feature! #1 #2 

Volume is unaffected and carries over into the recording. Pauses also carry over, the recorder just keeps running. (Theoretically it would be possible, but I had to use my own fork of Tone.js for resuming after a recorder.pause(). Also introduces complex timing issues.)
The core logic is extended based on events and promises, HTML/CSS is also simplified.

Example usage:
- Load track
- Play
- Press save or stop: Save stops and downloads the recording. Stop stops the recording, leaving the option to save manually. Both result in the stopped state where the next "Play" reinitializes the recorder.

### CODE REVIEW

**Comment by rupel190** [comment]
Hey @SophieShears do you wanna approve/close the PR? 🙂

**Comment by SophieShears** [comment]
Hey! Sorry it took me a while to get to this, I've been away from the project for a few years and busy lately. 

Love the changes, it looks great! A very fun feature!

The only issue is that running these changes locally I'm experiencing issues in Chrome 128.0.6613.120. Running it by default in chrome results in the load and save buttons being not interactable and blacked in the top left of the page out as seen in this screenshot:
Screenshot 2024-09-10 143525

However running it in an incognito window runs it fine, which is great! But I'm not entirely sure why it would run in incognito but not by default. I disabled all extensions while running it so they shouldn't cause an issue. 

But maybe you could make changes so it works by default in chrome?

Thanks!

**Comment by SophieShears** [comment]
Ahh ignore that last comment it works fine by default! Sorry I have been away for a while it must have been something on my end.

**Comment by SophieShears** [comment]
Huh no it does look like I'm experiencing the same thing. It works in an incognito browser but not by default on my version of chrome. Any ideas/ want to make another PR to address it?

**Comment by rupel190** [comment]
- Weird. Thanks for reviewing it, I'm definitely going to update, shouldn't be much! 🙂

**Comment by rupel190** [comment]
Hey again @SophieShears 
(unfortunately) it works for me in Chrome Version 128.0.6613.120 (Official Build) (64-bit)
and Edge Version 128.0.2739.67 (Official build) (64-bit). Both are fresh installs without profiles or addons.

Would you be so nice as to check the console? Maybe there are apparent JS or CSS issues. I'd also appreciate if we could recreate it on my side. 🤔
Here's my version which should be identical, but who knows, maybe it'll indicate a caching issue: https://rupel190.github.io/MidiToChiptune/

**Comment by SophieShears** [comment]
Well that's good to hear! It's now working for me this morning, both of our versions. 

Could have just been a caching issue but looks good now!

Thanks again!

**Pull request merged**
